spring.application.name=movie-backend

spring.datasource.url=jdbc:mysql://localhost:3306/movie_db
spring.datasource.username=root
spring.datasource.password=Chandu@7893

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

